//Default language
define({
    root:{
    	ALBUM: "Album",
    	ALBUMS: "Albums",
    	ALBUM_CANCEL: "Cancel",
    	ALBUM_CREATE_NEW: "Create new album",
    	ALBUM_DISPLAY_LIST: "Display in list",
    	ALBUM_DISPLAY_IMAGES: "Display in picture",
    	ALBUM_MY_ALBUMS: "My albums",
    	ALBUM_EMPTY_ALBUMS_LIST: "No album existing. Begin by creating a new one.",
    	ALBUM_SAVE_THIS_ALBUM: "Save",
    	ALBUM_DELETE_THIS_ALBUM: "Delete",
    	ALBUM_CONFIRM_DELETE: "Completely delete this album? Are you sure?",
    	ALBUM_PROPERTIES: "Properties",
    	ALBUM_BACK_TO_ALBUMS: "Back to albums",
    	ALBUM_BACK_TO_ALBUM: "Back to album",
    	ALBUM_SAVE_PROPERTIES: "Save",
    	ALBUM_VALIDATE: "Validate",
		ALBUM_PROPERTIES_SAVED: 'Properties have been saved.',
		ALBUM_TITLE_EMPTY_ERROR: "Title can't be empty to save properties.",
    	ALBUM_PROPERTIES_ALBUM: "Album properties",
    	ALBUM_TITLE: 'Title',
    	ALBUM_STARTDATE: 'Date',
    	ALBUM_MEDIA: 'Media',
    	ALBUM_TEXT: 'Text',
    	ALBUM_TEMPLATE: 'Template',
    	ALBUM_DROP_IMAGES: 'DROP YOUR PICTURES HERE',
    	ALBUM_ADD_TO_ALBUM: "TO ADD THEM IN THE ALBUM",
    	ALBUM_EMPTY_PHOTO_LIST: "No picture in the album. Send a picture to begin.",
    	ALBUM_OR: "or",
    	ALBUM_SEE_ONLINE: "Online version",
    	ALBUM_SHARE_ZONE: "Share Zone",
    	
    	ERROR_LOADING: "Loading error.",
    
        STARTDATE: 'Start Date',
        HEADLINE: 'Headline',
        TEXT: 'Text',
        MEDIA: 'Media',
        CREDIT: 'Credit',
        CAPTION: 'Caption',
        SAVE: "Save",
        SAVE_EVENT_TITLE: "Save the event",
        NEW_EVENT_LABEL: "New",
        NEW_EVENT_TITLE: "Create new element",
        DELETE: 'Delete',
        DROP_ZONE: "DROP IMAGE HERE",
    },
    
    //fr: true,
    'fr-fr' : true, 
    
       
});