define({
	ALBUM: "Album",
    ALBUMS: "Albums",
    ALBUM_CANCEL: "Annuler",
	ALBUM_CREATE_NEW: "Créer un album",
	ALBUM_DISPLAY_LIST: "Afficher en liste",
	ALBUM_DISPLAY_IMAGES: "Afficher en image",
	ALBUM_MY_ALBUMS: "Mes albums",
	ALBUM_EMPTY_ALBUMS_LIST: "Aucun album existant. Veuillez créer un nouvel album.",
	ALBUM_SAVE_THIS_ALBUM: "Enregistrer",
	ALBUM_DELETE_THIS_ALBUM: "Supprimer",
	ALBUM_CONFIRM_DELETE: "Etes-vous sûr de vouloir supprimer cet album?",
	ALBUM_PROPERTIES: "Propriétés",
	ALBUM_BACK_TO_ALBUMS: "Retour",
	ALBUM_BACK_TO_ALBUM: "Retour à l'album",
	ALBUM_SAVE_PROPERTIES: "Enregistrer",
	ALBUM_VALIDATE: "Valider",
	ALBUM_PROPERTIES_SAVED: 'Les propriétés sont sauvegardés',
	ALBUM_TITLE_EMPTY_ERROR: 'Le titre doit être remplie pour sauvegarder',
	ALBUM_PROPERTIES_ALBUM: "Propriétés de l'album",
	ALBUM_TITLE: 'Titre',
	ALBUM_STARTDATE: 'Date',
	ALBUM_MEDIA: 'Miniature',
	ALBUM_TEXT: 'Description',
	ALBUM_TEMPLATE: 'Affichage',
	ALBUM_DROP_IMAGES: 'GLISSER ICI VOS PHOTOS',
	ALBUM_ADD_TO_ALBUM: "POUR LES AJOUTER A L'ALBUM",
	ALBUM_EMPTY_PHOTO_LIST: "Aucune photo dans l'album. Commencer par envoyer une photo.",
    ALBUM_OR: "ou",
    ALBUM_SEE_ONLINE: "Voir en ligne",
    ALBUM_SHARE_ZONE: "Zone de partage",
    
	ERROR_LOADING: "Erreur de chargement.",

    STARTDATE: 'Date de début',
    HEADLINE: 'Titre',
    TEXT: 'Texte',
    MEDIA: 'Miniature',
    CREDIT: 'Référence',
    CAPTION: 'Légende',
    SAVE: "Sauvegarder",
    SAVE_EVENT_TITLE: "Sauvegarder l'evenement",
    NEW_EVENT_LABEL: "Nouveau",
    NEW_EVENT_TITLE: "Créer un nouvel élément",
    DELETE: 'Supprimer',
    DROP_ZONE: "GLISSER VOTRE IMAGE ICI",
});